package de.haw_landshut.hawmobile.base;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;
import de.haw_landshut.hawmobile.Fakultaet;

@Entity
public class FaecherData{

    @NonNull
    private Fakultaet studiengang;

    @ColumnInfo()
    private String fach;

    @PrimaryKey (autoGenerate = true)
    private long key;

    public FaecherData(Fakultaet studiengang, String fach){
        this.fach=fach;
        this.studiengang=studiengang;
    }


    public long getKey() {
        return key;
    }

    public void setKey(long key) {
        this.key = key;
    }

    public void setStudiengang(@NonNull Fakultaet studiengang) {
        this.studiengang = studiengang;
    }

    public void setFach(String fach) {
        this.fach = fach;
    }


    public Fakultaet getStudiengang(){
        return this.studiengang;
    }
    public String getFach(){
        return this.fach;
    }

    public static FaecherData[] populateSubjects(){
        return
                new FaecherData[]{

                        new FaecherData(Fakultaet.BW,"Wirtschaftsmathematik"),

                        new FaecherData(Fakultaet.BW,"Statistik"),

                        new FaecherData(Fakultaet.BW,"Volkswirtschaftslehre I Mikroökonomie"),

                        new FaecherData(Fakultaet.BW,"Volkswirtschaftslehre II Makroökonomie"),
                        new FaecherData(Fakultaet.BW,"Einführung in die Betriebswirtschaftslehre"),
                        new FaecherData(Fakultaet.BW,"Externes Rechnungswesen"),
                        new FaecherData(Fakultaet.BW,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.BW,"Informationstechnologie"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsenglisch"),
                        new FaecherData(Fakultaet.BW,"Foreign Business Language II"),
                        new FaecherData(Fakultaet.BW,"Principles of Marketing and Sales"),
                        new FaecherData(Fakultaet.BW,"Principles of Human Resource Management"),
                        new FaecherData(Fakultaet.BW,"Principles of Operations and Logistics Management"),
                        new FaecherData(Fakultaet.BW,"Principles of Finance and Investment"),
                        new FaecherData(Fakultaet.BW,"Principles of International Management"),
                        new FaecherData(Fakultaet.BW,"Principles of Organisation"),
                        new FaecherData(Fakultaet.BW,"European Law"),
                        new FaecherData(Fakultaet.BW,"Foreign Business Language II (Teil 2)"),
                        new FaecherData(Fakultaet.BW,"Business Administration Seminar"),
                        new FaecherData(Fakultaet.BW,"Digital Business Models"),
                        new FaecherData(Fakultaet.BW,"Fundamentals of International Economics"),
                        new FaecherData(Fakultaet.BW,"Specialised Compulsory Elective Module"),
                        new FaecherData(Fakultaet.BW,"Arbeitsrecht"),
                        new FaecherData(Fakultaet.BW,"Designing The Global Marketing Programme"),
                        new FaecherData(Fakultaet.BW,"Doing Business in Russia"),
                        new FaecherData(Fakultaet.BW,"Management Accounting and Control"),
                        new FaecherData(Fakultaet.BW,"Optimization in Logistics"),
                        new FaecherData(Fakultaet.BW,"Private Wealth Management"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsprivatrecht/Gesellschaftsrecht"),
                        new FaecherData(Fakultaet.BW,"Ingenieurmathematik I"),
                        new FaecherData(Fakultaet.BW,"Grundlagen der Elektrotechnik"),
                        new FaecherData(Fakultaet.BW,"Informatik I"),
                        new FaecherData(Fakultaet.BW,"Technische Mechanik"),
                        new FaecherData(Fakultaet.BW,"Grundlagen der Betriebs- und Volkswirtschaftslehre"),
                        new FaecherData(Fakultaet.BW,"Ingenieurmathematik II"),
                        new FaecherData(Fakultaet.BW,"Elektronik und Messtechnik"),
                        new FaecherData(Fakultaet.BW,"Informatik II"),
                        new FaecherData(Fakultaet.BW,"Angewandte Physik"),
                        new FaecherData(Fakultaet.BW,"Konstruktion und Entwicklung"),
                        new FaecherData(Fakultaet.BW,"Regelungstechnik"),
                        new FaecherData(Fakultaet.BW,"Mikrocomputertechnik"),
                        new FaecherData(Fakultaet.BW,"Buchführung und Bilanzierung"),
                        new FaecherData(Fakultaet.BW,"Grundlagen der Automobilwirtschaft"),
                        new FaecherData(Fakultaet.BW,"Marketing und Vertrieb"),
                        new FaecherData(Fakultaet.BW,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.BW,"Beschaffung, Produktion und Logistik"),
                        new FaecherData(Fakultaet.BW,"Finanz- und Investitionswirtschaft"),
                        new FaecherData(Fakultaet.BW,"Projektmanagement"),
                        new FaecherData(Fakultaet.BW,"Grundlagen der Produktionstechnik"),
                        new FaecherData(Fakultaet.BW,"Unternehmensplanspiel"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsprivatrecht"),
                        new FaecherData(Fakultaet.BW,"Produktions- und Prozessplanung"),
                        new FaecherData(Fakultaet.BW,"Logistik- und Fabrikplanung"),
                        new FaecherData(Fakultaet.BW,"Qualitätsmanagement"),
                        new FaecherData(Fakultaet.BW,"Technischer Einkauf"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsmathematik"),
                        new FaecherData(Fakultaet.BW,"Statistik"),
                        new FaecherData(Fakultaet.BW,"Volkswirtschaftslehre I Mikroökonomie"),
                        new FaecherData(Fakultaet.BW,"Volkswirtschaftslehre II Makroökonomie"),
                        new FaecherData(Fakultaet.BW,"Einführung in die Betriebswirtschaftslehre"),
                        new FaecherData(Fakultaet.BW,"Externes Rechnungswesen"),
                        new FaecherData(Fakultaet.BW,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.BW,"Informationstechnologie"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsenglisch"),
                        new FaecherData(Fakultaet.BW,"Grundlagen der Organisation"),
                        new FaecherData(Fakultaet.BW,"Grundlagen der Material- und Fertigungswirtschaft"),
                        new FaecherData(Fakultaet.BW,"Grundlagen des Personalmanagement"),
                        new FaecherData(Fakultaet.BW,"Grundlagen Marketing und Vertrieb"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsprivatrecht / Gesellschaftsrecht"),
                        new FaecherData(Fakultaet.BW,"Arbeitsrecht"),
                        new FaecherData(Fakultaet.BW,"Finanz- und Investitionswirtschaft"),
                        new FaecherData(Fakultaet.BW,"Steuern"),
                        new FaecherData(Fakultaet.BW,"Betriebswirtschaftliches Seminar"),
                        new FaecherData(Fakultaet.BW,"Betriebswirtschaftliche Entscheidungstechniken"),
                        new FaecherData(Fakultaet.BW,"Digital Business Models"),
                        new FaecherData(Fakultaet.BW,"Controlling und Finanzierung"),
                        new FaecherData(Fakultaet.BW,"Fundamentals of International Economics"),
                        new FaecherData(Fakultaet.BW,"Produkt- und Designmanagement"),
                        new FaecherData(Fakultaet.BW,"Datev I"),
                        new FaecherData(Fakultaet.BW,"Designing The Global Marketing Programme"),
                        new FaecherData(Fakultaet.BW,"Doing Business in Russia"),
                        new FaecherData(Fakultaet.BW,"Grundlagen des Facility-Managements / Principles of Facility Management"),
                        new FaecherData(Fakultaet.BW,"Management Accounting and Control"),
                        new FaecherData(Fakultaet.BW,"Optimization in Logistics"),
                        new FaecherData(Fakultaet.BW,"Private Wealth Management"),
                        new FaecherData(Fakultaet.BW,"Risikomanagement "),
                        new FaecherData(Fakultaet.BW,"Unternehmensführung"),
                        new FaecherData(Fakultaet.BW,"Politische ökonomie"),
                        new FaecherData(Fakultaet.BW,"Spezielle Steuerrechtsgebiete / Special taxes"),
                        new FaecherData(Fakultaet.BW,"Finanzmanagementkonzepte I"),
                        new FaecherData(Fakultaet.BW,"Finanzmanagementkonzepte II"),
                        new FaecherData(Fakultaet.BW,"Marketing- und Vertriebsmanagement I"),
                        new FaecherData(Fakultaet.BW,"Marketing- und Vertriebsmanagement II"),
                        new FaecherData(Fakultaet.BW,"Personalmanagement"),
                        new FaecherData(Fakultaet.BW,"Steuern I "),
                        new FaecherData(Fakultaet.BW,"Steuern II"),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsinformatik I "),
                        new FaecherData(Fakultaet.BW,"Wirtschaftsinformatik II "),
                        new FaecherData(Fakultaet.BW,"Beschaffung"),
                        new FaecherData(Fakultaet.BW,"Logistik"),
                        new FaecherData(Fakultaet.BW,"Rechnungslegung und Wirtschaftsprüfung I "),
                        new FaecherData(Fakultaet.BW,"Rechnungslegung und Wirtschaftsprüfung II"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik I"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Elektrotechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik I"),
                        new FaecherData(Fakultaet.EW,"Physik I"),
                        new FaecherData(Fakultaet.EW,"Biomedizinische Grundlagen I"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik II"),
                        new FaecherData(Fakultaet.EW,"Elektronik und Messtechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik II"),
                        new FaecherData(Fakultaet.EW,"Physik II"),
                        new FaecherData(Fakultaet.EW,"Biomedizinische Grundlagen II"),
                        new FaecherData(Fakultaet.EW,"Konstruktion und Entwicklung"),
                        new FaecherData(Fakultaet.EW,"Mikrocomputertechnik"),
                        new FaecherData(Fakultaet.EW,"Werkstoffe und Design in der Medizintechnik"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Betriebswirtschaftslehre"),
                        new FaecherData(Fakultaet.EW,"Sensorik in der Medizintechnik"),
                        new FaecherData(Fakultaet.EW,"Marketing und Vertrieb"),
                        new FaecherData(Fakultaet.EW,"Medizinische Bildverarbeitung"),
                        new FaecherData(Fakultaet.EW,"Qualitätsmanagement in der Medizintechnik"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der medizinischen Bildgebung"),
                        new FaecherData(Fakultaet.EW,"Projektmanagement"),
                        new FaecherData(Fakultaet.EW,"Regelungstechnik"),
                        new FaecherData(Fakultaet.EW,"Praktische Zeit im Betrieb"),
                        new FaecherData(Fakultaet.EW,"Softwareentwicklung in der Medizintechnik"),
                        new FaecherData(Fakultaet.EW,"Biosignalverarbeitung"),
                        new FaecherData(Fakultaet.EW,"Minimalinvasive Verfahren"),
                        new FaecherData(Fakultaet.EW,"Medizinische Optik und Lasertechnologie"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der medizinischen Gerätetechnik"),
                        new FaecherData(Fakultaet.EW,"Krankenhausorganisation"),
                        new FaecherData(Fakultaet.EW,"Systems Engineering in der Medizintechnik"),
                        new FaecherData(Fakultaet.EW,"Beschaffung, Produktion und Logistik"),
                        new FaecherData(Fakultaet.EW,"Technischer Einkauf"),
                        new FaecherData(Fakultaet.EW,"Rechnergestützte Messtechnik"),
                        new FaecherData(Fakultaet.EW,"Konstruktionsarbeit in der Medizintechnik"),
                        new FaecherData(Fakultaet.EW,"Produktmanagement und Technischer Vertrieb"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik I"),
                        new FaecherData(Fakultaet.EW,"Elektrotechnik I"),
                        new FaecherData(Fakultaet.EW,"Informatik I"),
                        new FaecherData(Fakultaet.EW,"Technische Mechanik"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik II"),
                        new FaecherData(Fakultaet.EW,"Elektrotechnik II"),
                        new FaecherData(Fakultaet.EW,"Informatik II "),
                        new FaecherData(Fakultaet.EW,"Angewandte Physik"),
                        new FaecherData(Fakultaet.EW,"Elektrotechnik III"),
                        new FaecherData(Fakultaet.EW,"Elektrische Messtechnik"),
                        new FaecherData(Fakultaet.EW,"Elektronische Bauelemente"),
                        new FaecherData(Fakultaet.EW,"Digitaltechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik III "),
                        new FaecherData(Fakultaet.EW,"Mikrocomputertechnik"),
                        new FaecherData(Fakultaet.EW,"Schaltungstechnik"),
                        new FaecherData(Fakultaet.EW,"Regelungstechnik I"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Energietechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik IV"),
                        new FaecherData(Fakultaet.EW,"Kommunikationstechnik"),
                        new FaecherData(Fakultaet.EW,"Mikrocontroller mit Echtzeitbetriebssystemen"),
                        new FaecherData(Fakultaet.EW,"Grundlagen elektrische Antriebe"),
                        new FaecherData(Fakultaet.EW,"Regelungstechnik II"),
                        new FaecherData(Fakultaet.EW,"Bussysteme"),
                        new FaecherData(Fakultaet.EW,"Leistungselektronik"),
                        new FaecherData(Fakultaet.EW,"Automatisierungstechnik"),
                        new FaecherData(Fakultaet.EW,"Energieversorgung in der Gebäudetechnik"),
                        new FaecherData(Fakultaet.EW,"Product Engineering in der Elektronikindustrie "),
                        new FaecherData(Fakultaet.EW,"Sensorik"),
                        new FaecherData(Fakultaet.EW,"Kommunikationssysteme"),
                        new FaecherData(Fakultaet.EW,"Marketing und Vertrieb"),
                        new FaecherData(Fakultaet.EW,"Projektarbeit in der Praxis"),
                        new FaecherData(Fakultaet.EW,"Robotik"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik I"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Elektrotechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik I"),
                        new FaecherData(Fakultaet.EW,"Technische Mechanik"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Betriebs- und Volkswirtschaftslehre"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik II"),
                        new FaecherData(Fakultaet.EW,"Elektronik und Messtechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik II"),
                        new FaecherData(Fakultaet.EW,"Angewandte Physik"),
                        new FaecherData(Fakultaet.EW,"Regelungstechnik"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Energiewirtschaft"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Energietechnik"),
                        new FaecherData(Fakultaet.EW,"Buchführung und Bilanzierung"),
                        new FaecherData(Fakultaet.EW,"Excel und VBA-Anwendungen"),
                        new FaecherData(Fakultaet.EW,"Marketing und Vertrieb"),
                        new FaecherData(Fakultaet.EW,"Energierecht und Regulierung"),
                        new FaecherData(Fakultaet.EW,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.EW,"Netztechnik und -führung"),
                        new FaecherData(Fakultaet.EW,"Finanz- und Investitionswirtschaft"),
                        new FaecherData(Fakultaet.EW,"Projektmanagement"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Produktionstechnik"),
                        new FaecherData(Fakultaet.EW,"Stromerzeugungstechnologien"),
                        new FaecherData(Fakultaet.EW,"Gas- und Kommunalwirtschaft"),
                        new FaecherData(Fakultaet.EW,"Energieeffizienz in Wohngebäuden"),
                        new FaecherData(Fakultaet.EW,"Aktuelle Managementthemen der Energiewirtschaft und -technik"),
                        new FaecherData(Fakultaet.EW,"Energie, Umwelt, Gesellschaft und Ethik"),
                        new FaecherData(Fakultaet.EW,"Energiehandel und Marktmechanismen"),
                        new FaecherData(Fakultaet.EW,"Energieeffizienz in Industrie und Gewerbe"),
                        new FaecherData(Fakultaet.EW,"Energieberatung für Wohngebäude"),
                        new FaecherData(Fakultaet.EW,"Technischer Einkauf"),
                        new FaecherData(Fakultaet.EW,"Sensorik"),
                        new FaecherData(Fakultaet.EW,"Automatisierungstechnik"),
                        new FaecherData(Fakultaet.EW,"Rechnergestützte Messtechnik"),
                        new FaecherData(Fakultaet.EW,"ERP-Systeme"),
                        new FaecherData(Fakultaet.EW,"Controlling"),
                        new FaecherData(Fakultaet.EW,"Geschäftsprozessmanagement"),
                        new FaecherData(Fakultaet.EW,"Wirtschaftsprivatrecht"),
                        new FaecherData(Fakultaet.EW,"Personalmanagement"),
                        new FaecherData(Fakultaet.EW,"Produktions- und Prozessplanung"),
                        new FaecherData(Fakultaet.EW,"Logistik- und Fabrikplanung"),
                        new FaecherData(Fakultaet.EW,"Datenbanksysteme und -anwendungen"),
                        new FaecherData(Fakultaet.EW,"Sensorik"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik I"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Elektrotechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik I"),
                        new FaecherData(Fakultaet.EW,"Technische Mechanik"),
                        new FaecherData(Fakultaet.EW,"Principles of Business Administration and Economics"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik II"),
                        new FaecherData(Fakultaet.EW,"Elektronik und Messtechnik "),
                        new FaecherData(Fakultaet.EW,"Informatik II"),
                        new FaecherData(Fakultaet.EW,"Applied Physics"),
                        new FaecherData(Fakultaet.EW,"Software-Tools"),
                        new FaecherData(Fakultaet.EW,"Buchführung und Bilanzierung"),
                        new FaecherData(Fakultaet.EW,"Prozessoptimierung und statistische Qualitätssicherung"),
                        new FaecherData(Fakultaet.EW,"Marketing and Sales"),
                        new FaecherData(Fakultaet.EW,"Konstruktion und Entwicklung"),
                        new FaecherData(Fakultaet.EW,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.EW,"Procurement, Manufacturing and Logistics"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Produktionstechnik"),
                        new FaecherData(Fakultaet.EW,"Finanz- und Investitionswirtschaft"),
                        new FaecherData(Fakultaet.EW,"Project Management"),
                        new FaecherData(Fakultaet.EW,"International Business and Cross-Cultural Communication"),
                        new FaecherData(Fakultaet.EW,"Energieversorgung in der Gebäudetechnik"),
                        new FaecherData(Fakultaet.EW,"Internettechnologien"),
                        new FaecherData(Fakultaet.EW,"Automatisierungstechnik "),
                        new FaecherData(Fakultaet.EW,"Telekommunikation"),
                        new FaecherData(Fakultaet.EW,"Rechnergestützte Messtechnik"),
                        new FaecherData(Fakultaet.EW,"Mikrocomputertechnik"),
                        new FaecherData(Fakultaet.EW,"Batteriespeicher"),
                        new FaecherData(Fakultaet.EW,"Unternehmensplanspiel"),
                        new FaecherData(Fakultaet.EW,"ERP-Systeme"),
                        new FaecherData(Fakultaet.EW,"Controlling "),
                        new FaecherData(Fakultaet.EW,"Geschäftsprozessmanagement "),
                        new FaecherData(Fakultaet.EW,"Wirtschaftsprivatrecht "),
                        new FaecherData(Fakultaet.EW,"Personalmanagement"),
                        new FaecherData(Fakultaet.EW,"Product Engineering in der Elektroindustrie"),
                        new FaecherData(Fakultaet.EW,"Produktions- und Prozessplanung"),
                        new FaecherData(Fakultaet.EW,"Logistik- und Fabrikplanung"),
                        new FaecherData(Fakultaet.EW,"Datenbanksysteme und -anwendungen"),
                        new FaecherData(Fakultaet.EW,"Qualitätsmanagement "),
                        new FaecherData(Fakultaet.EW,"Technischer Einkauf"),
                        new FaecherData(Fakultaet.EW,"Produktmanagement und Technischer Vertrieb"),
                        new FaecherData(Fakultaet.EW,"Internationale Beschaffung"),
                        new FaecherData(Fakultaet.EW,"International Production Networks and Logistik"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik I"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Elektrotechnik"),
                        new FaecherData(Fakultaet.EW,"Informatik I"),
                        new FaecherData(Fakultaet.EW,"Technische Mechanik"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Betriebs- und Volkswirtschaftslehre"),
                        new FaecherData(Fakultaet.EW,"Ingenieurmathematik II"),
                        new FaecherData(Fakultaet.EW,"Elektronik und Messtechnik "),
                        new FaecherData(Fakultaet.EW,"Informatik II"),
                        new FaecherData(Fakultaet.EW,"Angewandte Physik"),
                        new FaecherData(Fakultaet.EW,"Energiewirtschaft"),
                        new FaecherData(Fakultaet.EW,"Regelungstechnik"),
                        new FaecherData(Fakultaet.EW,"Buchführung und Bilanzierung"),
                        new FaecherData(Fakultaet.EW,"Marketing und Vertrieb"),
                        new FaecherData(Fakultaet.EW,"Grundlagen der Produktionstechnik"),
                        new FaecherData(Fakultaet.EW,"Konstruktion und Entwicklung"),
                        new FaecherData(Fakultaet.EW,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.EW,"Beschaffung, Produktion und Logistik"),
                        new FaecherData(Fakultaet.EW,"Finanz- und Investitionswirtschaft"),
                        new FaecherData(Fakultaet.EW,"Energieversorgung in der Gebäudetechnik"),
                        new FaecherData(Fakultaet.EW,"Sensorik"),
                        new FaecherData(Fakultaet.EW,"Internettechnologien"),
                        new FaecherData(Fakultaet.EW,"Automatisierungstechnik "),
                        new FaecherData(Fakultaet.EW,"Telekommunikation "),
                        new FaecherData(Fakultaet.EW,"Rechnergestützte Messtechnik"),
                        new FaecherData(Fakultaet.EW,"Batteriespeicher"),
                        new FaecherData(Fakultaet.EW,"Mikrocomputertechnik"),
                        new FaecherData(Fakultaet.EW,"Geschäftsprozessmanagement "),
                        new FaecherData(Fakultaet.EW,"Wirtschaftsprivatrecht"),
                        new FaecherData(Fakultaet.EW,"Personalmanagement"),
                        new FaecherData(Fakultaet.EW,"Produktions- und Prozessplanung"),
                        new FaecherData(Fakultaet.EW,"Logistik- und Fabrikplanung"),
                        new FaecherData(Fakultaet.EW,"Datenbanksysteme und -anwendungen"),
                        new FaecherData(Fakultaet.EW,"Qualitätsmanagement "),
                        new FaecherData(Fakultaet.EW,"Technischer Einkauf"),
                        new FaecherData(Fakultaet.EW,"Produktmanagement und Technischer Vertrieb"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit"),
                        new FaecherData(Fakultaet.SA,"Menschliches Verhalten, Entwicklung, Erziehung und Bildung"),
                        new FaecherData(Fakultaet.SA,"Theorien und Organisationen der Sozialen Arbeit"),
                        new FaecherData(Fakultaet.SA,"Gesellschaft und Politik"),
                        new FaecherData(Fakultaet.SA,"Strukturen des Rechts"),
                        new FaecherData(Fakultaet.SA,"Propädeutikum"),
                        new FaecherData(Fakultaet.SA,"Handlungskompetenz - Basisstrategien"),
                        new FaecherData(Fakultaet.SA,"Wissenschaft und Praxis Sozialer Arbeit"),
                        new FaecherData(Fakultaet.SA,"Sozialwissenschaftliche Forschung: Methoden und Projekte"),
                        new FaecherData(Fakultaet.SA,"Sozialleistungsrecht und Formen des Zusammenlebens"),
                        new FaecherData(Fakultaet.SA,"Handlungskompetenz Differenzielle Methoden"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und Kultur Kulturelle Differenzen"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und Gesundheit Theoretische Zugänge"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und sozialer Raum Theoretische Zugänge"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und soziale Ungleichheit Theoretische Zugänge"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und Kultur Interkulturelle Kompetenzen"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und Gesundheit Methoden Klinischer Sozialarbeit"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und sozialer Raum Methoden sozialräumlichen Arbeitens"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und soziale Ungleichheit Methoden im Umgang mit sozialer"),
                        new FaecherData(Fakultaet.SA,"Ungleichheit"),
                        new FaecherData(Fakultaet.SA,"Forschungs- und Entwicklungswerkstätten"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und Kultur Interkulturelle und gendersensible Praxis"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und Gesundheit Anwendungsfelder Klinischer Sozialarbeit"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und sozialer Raum Anwendungsfelder"),
                        new FaecherData(Fakultaet.SA,"Soziale Arbeit und soziale Ungleichheit Anwendungsfelder"),
                        new FaecherData(Fakultaet.SA,"Handlungskompetenz - Diagnostik und Fallarbeit"),
                        new FaecherData(Fakultaet.IF,"Grundlagen der Informatik"),
                        new FaecherData(Fakultaet.IF,"Grundlagen der theoretischen Informatik"),
                        new FaecherData(Fakultaet.IF,"Digitaltechnik"),
                        new FaecherData(Fakultaet.IF,"Mathematik 1"),
                        new FaecherData(Fakultaet.IF,"Mathematik 2"),
                        new FaecherData(Fakultaet.IF,"Software Engineering 1"),
                        new FaecherData(Fakultaet.IF,"Englisch"),
                        new FaecherData(Fakultaet.IF,"Programmieren 1"),
                        new FaecherData(Fakultaet.IF,"Programmieren 2"),
                        new FaecherData(Fakultaet.IF,"Programmieren 3"),
                        new FaecherData(Fakultaet.IF,"Software Engineering 2"),
                        new FaecherData(Fakultaet.IF,"Datenbanken"),
                        new FaecherData(Fakultaet.IF,"Rechnerarchitektur"),
                        new FaecherData(Fakultaet.IF,"Algorithmen und Datenstrukturen"),
                        new FaecherData(Fakultaet.IF,"Grundlagen der Betriebswirtschaftslehre"),
                        new FaecherData(Fakultaet.IF,"IT Sicherheit"),
                        new FaecherData(Fakultaet.IF,"Betriebssysteme"),
                        new FaecherData(Fakultaet.IF,"Datenkommunikation"),
                        new FaecherData(Fakultaet.IF,"Statistik"),
                        new FaecherData(Fakultaet.IF,"Präsentation und Kommunikation"),
                        new FaecherData(Fakultaet.IF,"Praktikum"),
                        new FaecherData(Fakultaet.IF,"Praxisseminar"),
                        new FaecherData(Fakultaet.IF,"IT-Recht"),
                        new FaecherData(Fakultaet.IF,"Grundlagen Projektmanagement/Projektcontrolling"),
                        new FaecherData(Fakultaet.IF,"Numerik"),
                        new FaecherData(Fakultaet.IF,"Compiler"),
                        new FaecherData(Fakultaet.IF,"Verteilte System"),
                        new FaecherData(Fakultaet.IF,"Internettechnologien"),
                        new FaecherData(Fakultaet.IF,"Prozessrechentechnik"),
                        new FaecherData(Fakultaet.IF,"Grundlagen der Wirtschaftsinformatik"),
                        new FaecherData(Fakultaet.IF,"BWL Basismodul (Teil: Einführung BW"),
                        new FaecherData(Fakultaet.IF,"BWL Basismodul (Teil: Buchführung"),
                        new FaecherData(Fakultaet.IF,"Software Engineering 1"),
                        new FaecherData(Fakultaet.IF,"Finanzen und Investition"),
                        new FaecherData(Fakultaet.IF,"Englisch"),
                        new FaecherData(Fakultaet.IF,"Software Engineering 2"),
                        new FaecherData(Fakultaet.IF,"Datenbanken"),
                        new FaecherData(Fakultaet.IF,"Statistik"),
                        new FaecherData(Fakultaet.IF,"Geschäftsprozesse und Organisation"),
                        new FaecherData(Fakultaet.IF,"Algorithmen und Datenstrukturen"),
                        new FaecherData(Fakultaet.IF,"IT-Infrastrukturen"),
                        new FaecherData(Fakultaet.IF,"Kosten- und Leistungsrechnung"),
                        new FaecherData(Fakultaet.IF,"Material und Fertigungswirtschaft/Logistik"),
                        new FaecherData(Fakultaet.IF,"Operations Research"),
                        new FaecherData(Fakultaet.IF,"IT-Compliance und IT-Recht"),
                        new FaecherData(Fakultaet.IF,"Praxisorientiertes Studienprojekt"),
                        new FaecherData(Fakultaet.IF,"IT-Projektmanagement"),
                        new FaecherData(Fakultaet.IF,"Praktische Zeit im Betrieb"),
                        new FaecherData(Fakultaet.IF,"Praxisseminar"),
                        new FaecherData(Fakultaet.IF,"Internettechnologien"),
                        new FaecherData(Fakultaet.IF,"Software Engineering 3"),
                        new FaecherData(Fakultaet.IF,"IT-Sicherheit"),
                        new FaecherData(Fakultaet.IF,"IT-Management und -Controlling"),
                        new FaecherData(Fakultaet.IF,"Unternehmenssoftware (ERP-System"),
                        new FaecherData(Fakultaet.IF,"Controlling-Praxis im Unternehmen"),
                        new FaecherData(Fakultaet.IF,"Doing Business in Russia"),
                        new FaecherData(Fakultaet.IF,"Revenue Management"),
                        new FaecherData(Fakultaet.IF,"Informations- und Metamodellierung"),
                        new FaecherData(Fakultaet.IF,"Enterprise Computing"),
                        new FaecherData(Fakultaet.IF,"Sicherheit mobiler System"),
                        new FaecherData(Fakultaet.IF,"Internet of Things (IoT"),
                        new FaecherData(Fakultaet.IF,"Innovationslaber (IoT-Projekt"),
                        new FaecherData(Fakultaet.IF,"Mobile Business"),
                        new FaecherData(Fakultaet.IF,"Wahlpflichtmodul BW"),
                        new FaecherData(Fakultaet.IF,"Wahlpflichtmodul IF"),
                        new FaecherData(Fakultaet.IF,"Dirigieren"),
                        new FaecherData(Fakultaet.IF,"Digitaltechnik"),
                        new FaecherData(Fakultaet.IF,"Grundlagen der Elektrotechnik"),
                        new FaecherData(Fakultaet.IF,"Technische Mechanik"),
                        new FaecherData(Fakultaet.IF,"Software Engineering"),
                        new FaecherData(Fakultaet.IF,"Ingenieurmathematik 1"),
                        new FaecherData(Fakultaet.IF,"Ingenieurmathematik 2"),
                        new FaecherData(Fakultaet.IF,"Elektronik und Messtechnik"),
                        new FaecherData(Fakultaet.IF,"Angewandte Physik"),
                        new FaecherData(Fakultaet.IF,"Datenbanken"),
                        new FaecherData(Fakultaet.IF,"Regelungstechnik"),
                        new FaecherData(Fakultaet.IF,"Konstruktion und Entwicklung"),
                        new FaecherData(Fakultaet.IF,"Rechnerarchitektur"),
                        new FaecherData(Fakultaet.IF,"Algorithmen und Datenstrukturen"),
                        new FaecherData(Fakultaet.IF,"Grundlagen der Automobiltechnik"),
                        new FaecherData(Fakultaet.IF,"Fahrwerktechnik"),
                        new FaecherData(Fakultaet.IF,"Antriebstechnik"),
                        new FaecherData(Fakultaet.IF,"Prozessrechentechnik"),
                        new FaecherData(Fakultaet.IF,"Karosserietechnik"),
                        new FaecherData(Fakultaet.MA,"Naturwissenschaftliche Grundlagen "),
                        new FaecherData(Fakultaet.MA,"Maschinenkonstruktion I "),
                        new FaecherData(Fakultaet.MA,"Wirtschaftliche und soziale Kompetenzen "),
                        new FaecherData(Fakultaet.MA,"Ingenieurmathematik"),
                        new FaecherData(Fakultaet.MA,"Werkstoffkunde"),
                        new FaecherData(Fakultaet.MA,"Technische Mechanik "),
                        new FaecherData(Fakultaet.MA,"Grundlagen Ingenieurinformatik"),
                        new FaecherData(Fakultaet.MA,"Festigkeitslehre"),
                        new FaecherData(Fakultaet.MA,"Ingenieurmathematik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen, Elektrotechnik und Elektronik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen Fertigungstechnik"),
                        new FaecherData(Fakultaet.MA,"Versuchstechnik "),
                        new FaecherData(Fakultaet.MA,"Strömungsmechanik "),
                        new FaecherData(Fakultaet.MA,"Technische Thermodynamik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen CAD/FEM"),
                        new FaecherData(Fakultaet.MA,"Steuerungs- und Regelungstechnik"),
                        new FaecherData(Fakultaet.MA,"Maschinenkonstruktion II"),
                        new FaecherData(Fakultaet.MA,"Elektrische Antriebe und Getriebetechnik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen Leichtbau"),
                        new FaecherData(Fakultaet.MA,"Produktionsmanagement"),
                        new FaecherData(Fakultaet.MA,"Umwelttechnik "),
                        new FaecherData(Fakultaet.MA,"Werkstoffe und Betriebsfestigkeit "),
                        new FaecherData(Fakultaet.MA,"Werkzeugmaschinen und Automatisierungstechnik"),
                        new FaecherData(Fakultaet.MA,"Wärme- und Fluidtechnik "),
                        new FaecherData(Fakultaet.MA,"Gießereitechnik und Schweißtechnik"),
                        new FaecherData(Fakultaet.MA,"Entwicklung dynamischer Systeme "),
                        new FaecherData(Fakultaet.MA,"Energietechnik 1 "),
                        new FaecherData(Fakultaet.MA,"Energietechnik 2 "),
                        new FaecherData(Fakultaet.MA,"Energietechnik 3 "),
                        new FaecherData(Fakultaet.MA,"Energie-/Umweltmanagement"),
                        new FaecherData(Fakultaet.MA,"Energiewirtschaft/Energieeffizienz"),
                        new FaecherData(Fakultaet.MA,"Vertiefende Fertigungstechnik 1"),
                        new FaecherData(Fakultaet.MA,"Werkzeugmaschinen und Automatisierungstechnik"),
                        new FaecherData(Fakultaet.MA,"Qualitätsmanagement und Unternehmensführung "),
                        new FaecherData(Fakultaet.MA,"Vertiefende Fertigungstechnik 2 "),
                        new FaecherData(Fakultaet.MA,"Produktionslogistik und Investitionsmanagement"),
                        new FaecherData(Fakultaet.MA,"Konstruktionswerkstoffe für den Leichtbau"),
                        new FaecherData(Fakultaet.MA,"Leichtbaustrukturen"),
                        new FaecherData(Fakultaet.MA,"Wärme- und Fluidtechnik"),
                        new FaecherData(Fakultaet.MA,"Fertigungstechnologien für den Leichtbau"),
                        new FaecherData(Fakultaet.MA,"Entwicklung dynamischer Systeme"),
                        new FaecherData(Fakultaet.MA,"Faserverbundwerkstoffe"),
                        new FaecherData(Fakultaet.MA,"Prozesseffizienz und Ressourcenmanagement in der Fertigung "),
                        new FaecherData(Fakultaet.MA,"Stoffstrommanagement und Abfallwirtschaft"),
                        new FaecherData(Fakultaet.MA,"Industriemarketing und technische Betriebsführung"),
                        new FaecherData(Fakultaet.MA,"Vertiefung CAD "),
                        new FaecherData(Fakultaet.MA,"Strömungsmaschinen"),
                        new FaecherData(Fakultaet.MA,"Ingenieurmathematik"),
                        new FaecherData(Fakultaet.MA,"Ingenieurinformatik"),
                        new FaecherData(Fakultaet.MA,"Naturwissenschaftliche Grundlagen"),
                        new FaecherData(Fakultaet.MA,"Materialkunde"),
                        new FaecherData(Fakultaet.MA,"Technische Mechanik I "),
                        new FaecherData(Fakultaet.MA,"Technische Mechanik II "),
                        new FaecherData(Fakultaet.MA,"Maschinenkonstruktion I "),
                        new FaecherData(Fakultaet.MA,"Maschinenkonstruktion II"),
                        new FaecherData(Fakultaet.MA,"Elektro- und Messtechnik "),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Fertigungstechnik"),
                        new FaecherData(Fakultaet.MA,"Interdisziplinäre Fächer"),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Energietechnik "),
                        new FaecherData(Fakultaet.MA,"Konstruktion und CAD"),
                        new FaecherData(Fakultaet.MA,"Finite Elemente"),
                        new FaecherData(Fakultaet.MA,"Automatisierungs- und Versuchstechnik"),
                        new FaecherData(Fakultaet.MA,"Werkstoffe und Leichtbau I "),
                        new FaecherData(Fakultaet.MA,"Konstruktionsarbeit"),
                        new FaecherData(Fakultaet.MA,"Erweiterte Energietechnik"),
                        new FaecherData(Fakultaet.MA,"Werkstoffe und Leichtbau II"),
                        new FaecherData(Fakultaet.MA,"Ingenieurwissenschaftliche Praktika"),
                        new FaecherData(Fakultaet.MA,"Leichtbaumechanik"),
                        new FaecherData(Fakultaet.MA,"Prozesstechnologie im Strukturleichtbau"),
                        new FaecherData(Fakultaet.MA,"Naturwissenschaftliche Grundlagen"),
                        new FaecherData(Fakultaet.MA,"Maschinenkonstruktion I"),
                        new FaecherData(Fakultaet.MA,"Wirtschaftliche und soziale Kompetenzen "),
                        new FaecherData(Fakultaet.MA,"Ingenieurmathematik"),
                        new FaecherData(Fakultaet.MA,"Werkstoffkunde"),
                        new FaecherData(Fakultaet.MA,"Technische Mechanik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen Ingenieurinformatik"),
                        new FaecherData(Fakultaet.MA,"Festigkeitslehre"),
                        new FaecherData(Fakultaet.MA,"Maschinenelemente"),
                        new FaecherData(Fakultaet.MA,"Grundlagen  Elektrotechnik und Elektronik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen Fertigungstechnik"),
                        new FaecherData(Fakultaet.MA,"Versuchstechnik"),
                        new FaecherData(Fakultaet.MA,"Strömungsmechanik"),
                        new FaecherData(Fakultaet.MA,"Technische Thermodynamik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen CAD/FEM"),
                        new FaecherData(Fakultaet.MA,"Steuerungs- und Regelungstechnik"),
                        new FaecherData(Fakultaet.MA,"Maschinenkonstruktion II"),
                        new FaecherData(Fakultaet.MA,"Verbrennungsmotoren"),
                        new FaecherData(Fakultaet.MA,"Praktisches Studiensemester"),
                        new FaecherData(Fakultaet.MA,"Projektarbeit"),
                        new FaecherData(Fakultaet.MA,"Ingenieurtechnisches Praktikum"),
                        new FaecherData(Fakultaet.MA,"Fahrzeuginformatik"),
                        new FaecherData(Fakultaet.MA,"Automobiltechnik I"),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Antriebstechnik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Fahrzeugmechatronik"),
                        new FaecherData(Fakultaet.MA,"Automobiltechnik II"),
                        new FaecherData(Fakultaet.MA,"Fahrzeuginformatik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Antriebstechnik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen moderner NFZ"),
                        new FaecherData(Fakultaet.MA,"Moderne NFZ Technik I"),
                        new FaecherData(Fakultaet.MA,"Moderne NFZ Technik II"),
                        new FaecherData(Fakultaet.MA,"Fahrzeuginformatik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Antriebstechnik"),
                        new FaecherData(Fakultaet.MA,"Grundlagen der Fahrzeugmechatronik"),
                        new FaecherData(Fakultaet.MA,"Alternative Antriebstechniken"),
                        new FaecherData(Fakultaet.MA,"Entwicklung dynamischer Systeme"),
                        new FaecherData(Fakultaet.MA,"Qualitätsmanagement und Unternehmensführung"),
                        new FaecherData(Fakultaet.MA,"Konstruktionswerkstoffe für den Leichtbau"),
                        new FaecherData(Fakultaet.MA,"Leichtbaustrukturen")



                };
    }
}